name: Déploiement sur Azure Functions

on:
  push:
    branches:
      - master

jobs:

  deploiement:

    if: github.actor == 'axel-op'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Formattage
        uses: axel-op/googlejavaformat-action@master
        with:
          args: "--aosp --skip-sorting-imports -r"
          skipCommit: true
      - name: Installation d'Azure Functions Core Tools
        run: |
          wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install azure-functions-core-tools
      - name: Compilation
        run: mvn --batch-mode clean package --file pom.xml
      - name: Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Déploiement
        uses: azure/webapps-deploy@v1
        with:
          app-name: mesmedicaments
      - name: Commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email ""
          git commit -m "Formate + compile" -a
          git push
        
      
