name: Déploiement sur Azure Functions

on:
  push:
    branches:
      - master

jobs:
  deploiement:
    env:
      format: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installation d'Amazon Corretto
        run: |
          wget -O- https://apt.corretto.aws/corretto.key | sudo apt-key add - 
          sudo add-apt-repository 'deb https://apt.corretto.aws stable main'
          sudo apt-get update
          sudo apt-get install -y java-1.8.0-amazon-corretto-jdk

      - name: Formatage
        if: env.format == 'true'
        uses: axel-op/googlejavaformat-action@master
        with:
          args: "--aosp --skip-sorting-imports -r"
          skipCommit: true

      - name: Installation d'Azure Functions Core Tools
        run: |
          wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install azure-functions-core-tools

      - name: Compilation
        run: mvn --batch-mode clean package --file pom.xml

      - name: Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Déploiement
        uses: azure/webapps-deploy@v1
        with:
          app-name: mesmedicaments

      - name: Commit
        if: env.format == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email ""
          git commit -m "Formate" -a
          git push
