name: Format

on:
  push:
    branches:
      - master

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/googlejavaformat-action@master
        with:
          args: "--aosp -r"