name: Image pour la maintenance

on:
  push:
    branches:
      - master
    paths:
      '**.java'

jobs:

  build:

    if: github.actor == 'axel-op'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build and push image
        env:
          DOCKERFILE: .github/workflows/Dockerfile
          IMAGE: axelop/mesmedicaments-maintenance
          USERNAME: axelop
          TOKEN: ${{ secrets.DOCKER_TOKEN }}
          LABEL: latest
        run: |
          wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install azure-functions-core-tools
          mvn --batch-mode clean package
          sudo docker build -f $DOCKERFILE -t $IMAGE:$LABEL .
          echo $TOKEN | sudo docker login --username=$USERNAME --password-stdin
          sudo docker push $IMAGE:$LABEL

