name: Image pour la maintenance

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/image-maintenance.yml"
      - "**.java"
      - "*.json"
      - "*.csproj"

jobs:
  build:
    if: github.actor == 'axel-op'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
          server-password: MAVEN_GITHUB_TOKEN
      - name: Build and push image
        env:
          MAVEN_GITHUB_TOKEN: ${{ secrets.MAVEN_PAT }}
          DOCKERFILE: .github/workflows/Dockerfile
          IMAGE: axelop/mesmedicaments-maintenance
          USERNAME: axelop
          TOKEN: ${{ secrets.DOCKER_TOKEN }}
          LABEL: latest
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list'
          sudo apt-get update
          sudo apt-get install azure-functions-core-tools-3
          mvn --batch-mode clean package
          sudo docker build -f $DOCKERFILE -t $IMAGE:$LABEL .
          echo $TOKEN | sudo docker login --username=$USERNAME --password-stdin
          sudo docker push $IMAGE:$LABEL
