name: Exécution de la maintenance sur Azure

on:
  schedule:
    - cron: "0 0 1/15 * *"

jobs:

  run:
    
    runs-on: ubuntu-latest

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy and launch on Azure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az container create \
              --resource-group mesmedicaments \
              --location westeurope \
              --name maintenance-$(date +'%m-%d-%Y') \
              --secure-environment-variables "AzureWebJobsStorage"="${{ secrets.AZURE_STORAGE }}" \
              --ip-address private \
              --restart-policy Never \
              --image axelop/mesmedicaments-maintenance \
              --registry-login-server index.docker.io \
              --registry-username axelop \
              --registry-password ${{ secrets.DOCKER_TOKEN }}
